events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Todo lo que empiece con /api/ va hacia Gunicorn (Backend)
        location /api/ {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Todo lo demás (la raíz) va hacia Astro (Frontend)
        location / {
            proxy_pass http://frontend-astro:4321;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}